# Generated by Django 6.0 on 2025-12-18 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('raqami', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='TestBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('yaratilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_blocklari', to='my_app.kurs')),
            ],
            options={
                'verbose_name': 'Test Block',
                'verbose_name_plural': 'Test Blocklar',
            },
        ),
        migrations.CreateModel(
            name='Savol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField()),
                ('variant_a', models.CharField(max_length=500)),
                ('variant_b', models.CharField(max_length=500)),
                ('variant_c', models.CharField(max_length=500)),
                ('variant_d', models.CharField(max_length=500)),
                ('togri_javob', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savollar', to='my_app.testblock')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
            },
        ),
        migrations.CreateModel(
            name='TestNatija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('togri_javoblar', models.IntegerField(default=0)),
                ('xato_javoblar', models.IntegerField(default=0)),
                ('vaqt_sekund', models.IntegerField()),
                ('topshirilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.testblock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test Natijasi',
                'verbose_name_plural': 'Test Natijalari',
            },
        ),
    ]
