# Generated by Django 6.0 on 2025-12-22 16:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kurs nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Guruh nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='my_app.course', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', related_query_name='custom_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', related_query_name='custom_user', to='auth.permission', verbose_name='user permissions')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='my_app.group', verbose_name='Guruh')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TestBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Test nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('start_time', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('time_per_question', models.IntegerField(default=2, verbose_name='Har bir savol uchun vaqt (daqiqa)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_blocks', to='my_app.course', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Test bloki',
                'verbose_name_plural': 'Test bloklari',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Savol matni')),
                ('option_a', models.CharField(max_length=500, verbose_name='A variant')),
                ('option_b', models.CharField(max_length=500, verbose_name='B variant')),
                ('option_c', models.CharField(max_length=500, verbose_name='C variant')),
                ('option_d', models.CharField(max_length=500, verbose_name='D variant')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name="To'g'ri javob")),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('test_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='my_app.testblock', verbose_name='Test bloki')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Ball')),
                ('total_questions', models.IntegerField(default=0, verbose_name='Jami savollar')),
                ('correct_answers', models.IntegerField(default=0, verbose_name="To'g'ri javoblar")),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Topshirilgan vaqt')),
                ('time_spent', models.IntegerField(default=0, verbose_name='Sarflangan vaqt (soniya)')),
                ('test_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='my_app.testblock', verbose_name='Test bloki')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='my_app.customuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Test natijasi',
                'verbose_name_plural': 'Test natijalari',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Tanlangan javob')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri javob")),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Javob berilgan vaqt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='my_app.question', verbose_name='Savol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='my_app.customuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi javobi',
                'verbose_name_plural': 'Foydalanuvchi javoblari',
                'unique_together': {('user', 'question')},
            },
        ),
    ]
