# Generated by Django 6.0 on 2025-12-19 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testnatija',
            options={'ordering': ['-topshirilgan_vaqt'], 'verbose_name': 'Test Natijasi', 'verbose_name_plural': 'Test Natijalari'},
        ),
        migrations.AddField(
            model_name='testblock',
            name='block_turi',
            field=models.CharField(choices=[('ochiq', 'Ochiq test'), ('yopiq', 'Yopiq test')], default='ochiq', max_length=10),
        ),
        migrations.AddField(
            model_name='testblock',
            name='boshlash_vaqti',
            field=models.DateTimeField(blank=True, help_text='Test boshlash vaqti', null=True),
        ),
        migrations.AddField(
            model_name='testblock',
            name='savol_vaqti',
            field=models.IntegerField(default=60, help_text='Har bir savol uchun vaqt (soniyada)'),
        ),
        migrations.AddField(
            model_name='testblock',
            name='tanlangan_userlar',
            field=models.ManyToManyField(blank=True, related_name='ruxsat_berilgan_testlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testblock',
            name='tugash_vaqti',
            field=models.DateTimeField(blank=True, help_text='Test tugash vaqti', null=True),
        ),
        migrations.AddField(
            model_name='testblock',
            name='vaqt_turi',
            field=models.CharField(choices=[('vaqtli', 'Vaqtli'), ('vaqtsiz', 'Vaqtsiz')], default='vaqtsiz', max_length=10),
        ),
        migrations.AddField(
            model_name='testnatija',
            name='jami_savollar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testnatija',
            name='javoblar',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='testnatija',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natijalar', to='my_app.testblock'),
        ),
        migrations.CreateModel(
            name='RetestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabab', models.TextField(help_text='Qayta test ishlash uchun sabab')),
                ('status', models.CharField(choices=[('kutilmoqda', 'Kutilmoqda'), ('tasdiqlandi', 'Tasdiqlandi'), ('rad_etildi', 'Rad etildi')], default='kutilmoqda', max_length=15)),
                ('yuborilgan_vaqt', models.DateTimeField(auto_now_add=True)),
                ('admin_javobi', models.TextField(blank=True, null=True)),
                ('korilgan_vaqt', models.DateTimeField(blank=True, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retest_requests', to='my_app.testblock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retest_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Qayta Test So'rovi",
                'verbose_name_plural': "Qayta Test So'rovlari",
                'ordering': ['-yuborilgan_vaqt'],
            },
        ),
    ]
