# Generated by Django 6.0 on 2025-12-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_testnatija_options_testblock_block_turi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savol',
            name='rasm',
            field=models.ImageField(blank=True, help_text="Savolga rasm qo'shish (majburiy emas)", null=True, upload_to='savol_rasmlari/'),
        ),
    ]
